language: java
script: mvn verify
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: QnzkE05BFanZstCrlGU7WeJD0si3x9aYuP+MF3HqcEq8ufFvGNrpTypyhju4PCPySUWKOD8CITECyQmEOoKDHyHw7fqzQz/VUldsicvEpb+1brnhBP9N16je2/a/Kayvk/AgPd7VC8Wcu8J6ob/p+SsFOY7pDOlITOcGIgJoemqlHCJnYt6HWzfmo/NG8vHERE0hLIb6LpMgyUCN8hvIUsl5MoW+kdYBNCjKP4gqqH0BBl1MofB7JJWIhy+xpdTOtqIatkiT4eNXIp7G2VwBT2W2YOPX0hje9BDKE6k8dE7UltDZ6by88zM5CKJD9JvE57v2PBy+cSegfLhk01RZYmoSayh8uLWV8c1iVPsdJU6MvWyMb6Hgx/8J8k9FO2ms5Zaid2R2pJ5QIj0pwlj+dCLib3gcYXeYBUCyINUoor6v7uL3EHrwKofl5la3YALyA1QpmjoBtIXtRu6fEEZJUqivz51pkzZSl64AGlku9Of1ekmtObvbjDuns96JwYCEDk0/889gSYLPOp7gRfAk/FDdmubYle745ad+BK3fbuGX9SZoQHxTfD2abiL2cfPqJV+RAOW4MUM4zP9cSXOvQl6Ow4L6xGxaJ1aX65Mp1A2P8BmCj+Icg/W0HtIdInEw0L0LiuyIlbcwerlFWtrrhL0mDzfAL2Ghavj9Lon62Mw=
